version: 1.0.{build}

image: Visual Studio 2013

environment:
  matrix:
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-msvc

install:
- appveyor DownloadFile https://static.rust-lang.org/dist/rust-beta-%TARGET%.exe
- rust-beta-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
- SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
- SET PATH=%PATH%;C:\MinGW\bin
- rustc -V
- cargo -V

cache:
- target
- C:\Users\appveyor\.cargo\registry

build_script:
- cargo build --target %TARGET% --release
- move target\%TARGET%\release\airjump-multi.exe airjump-multi-%TARGET%.exe

artifacts:
- path: airjump-multi-%TARGET%.exe
  name: airjump-multi-%TARGET%.exe
